# Generated by Django 4.1.2 on 2023-01-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(max_length=100)),
                ('total', models.CharField(max_length=100)),
            ],
        ),
    ]
