# Generated by Django 4.1.2 on 2023-01-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketWeb', '0002_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
    ]
