# Generated by Django 4.1.2 on 2023-01-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketWeb', '0003_cartdb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='quantity',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cartdb',
            name='total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
