# Generated by Django 4.1.2 on 2023-01-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketWeb', '0004_alter_cartdb_quantity_alter_cartdb_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
