# Generated by Django 4.1.2 on 2023-01-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketWeb', '0005_alter_cartdb_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdb',
            name='image',
        ),
        migrations.AlterField(
            model_name='cartdb',
            name='total',
            field=models.CharField(max_length=100),
        ),
    ]
