# Generated by Django 4.1.2 on 2023-01-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketWeb', '0007_cartdb_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdb',
            old_name='price',
            new_name='ProductName',
        ),
        migrations.RenameField(
            model_name='cartdb',
            old_name='quantity',
            new_name='Quantity',
        ),
        migrations.RemoveField(
            model_name='cartdb',
            name='productname',
        ),
        migrations.RemoveField(
            model_name='cartdb',
            name='total',
        ),
        migrations.AlterField(
            model_name='cartdb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
        migrations.AddField(
            model_name='cartdb',
            name='Total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
