# Generated by Django 4.1.2 on 2023-01-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketWeb', '0008_rename_price_cartdb_productname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdb',
            name='ProductName',
        ),
        migrations.AddField(
            model_name='cartdb',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
