# Generated by Django 4.1.2 on 2023-01-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketWeb', '0009_remove_cartdb_productname_cartdb_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartdb',
        ),
    ]
