# Generated by Django 4.1.2 on 2023-01-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketWeb', '0012_rename_cartdb_cartdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cartdetails',
            new_name='cartdb',
        ),
    ]
