# Generated by Django 4.1.2 on 2023-01-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketWeb', '0013_rename_cartdetails_cartdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdb',
            name='product',
        ),
        migrations.AddField(
            model_name='cartdb',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
