# Generated by Django 4.1.2 on 2023-01-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketWeb', '0014_remove_cartdb_product_cartdb_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdb',
            old_name='Name',
            new_name='Product',
        ),
    ]
